name: dask-tutorial-advanced
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dask=2023.6.1
  - python-graphviz
  - imageio
  - scipy
  - matplotlib
  - pip
  - pyarrow
  - s3fs
  # JupyterLab + extensions
  - jupyterlab>=3,<4
  - dask-labextension
  - ipywidgets